name: Publish Release

on:
    release:
        types: [ published ]

jobs:
  publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.ref }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        always-auth: true
        node-version: ${{ matrix.node-version }}
        registry-url: https://npmjs.org
        scope: '@neerinc'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Publish package
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      working-directory: ./dist
